FROM python:3.9-slim

COPY requirements.txt requirements.txt

RUN apt-get update && \
apt-get install --no-install-recommends -y vim && \
rm -rf /var/lib/apt/lists/* && \
pip install --no-cache-dir --upgrade -r requirements.txt
