image : registry.gitlab.si.francetelecom.fr/lrousselotdesaintceran/co-tools-api-middleware/base/co-tools-test

checker:
    stage: pre
    script:
      - flake8 .
    allow_failure: false

formater:
    stage: pre
    script:
      - black --check .
    allow_failure: true
    except:
      - develop
      - master
