retager:
    image: sfy-search-registry-build.artifactory.si.francetelecom.fr/build/docker:dind
    stage: retager
    before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:
      - docker pull $IMAGE_NAME:$CI_COMMIT_REF_SLUG
      - docker push $IMAGE_NAME:$CI_COMMIT_BRANCH
    allow_failure: false
    only:
      - develop
