unit-tester:
  image: registry.gitlab.si.francetelecom.fr/lrousselotdesaintceran/co-tools-api-middleware/base/co-tools-test
  stage: unit-test
  before_script:
      - export PYTHONPATH=.
  script:
    - pytest tests/unit/ --junitxml=report_unit.xml
  allow_failure: false
  artifacts:
    when: always
    reports:
      junit: report_unit.xml
  except:
    - develop
    - master
